### PR TITLE
Add cmake option to support pybind11 from conda

### PR DESCRIPTION
**Pull request by Krande**
As discussed in https://github.com/wassimj/topologicpy/issues/71 here is a proposed change to the Topologic cmake build scripts that adds an option of using pybind11 as a conda dependency not only as a git submodule.

Regarding updating the readme, I am not 100% sure what to write really. This proposal doesn't really affect the current build suggestions. It just adds an option to pass in `-DUSE_CONDA_PYBIND11=ON` to let cmake discover pybind11 using the regular PREFIX paths used by conda.

Before I add anything to the readme i just wanted to get your thoughts on;

I guess for users that are looking for the straightest path to install Topologic into their existing pip/conda environment, maybe it would be a good idea to add a section with the installation instructions using the main package repositories, such as `pip install topologic-core` and `conda install topologic-core`. 

For local development, I could make a suggestion using [pixi](https://pixi.sh/latest/) to replace all the different build scripts and conda environments? A `pixi.toml` file is designed to solve exactly that (multiple environments and various scripts/tasks),

FYI: I have made a PR for topologic for conda-forge -> https://github.com/conda-forge/staged-recipes/pull/28262 (Note that conda-forge is currently having some issues with their osx ci's today, so it might take a day or two before it gets resolved and we can finalize adding the package to conda-forge). Once topologic-core is added to conda-forge I'll start on topologicpy.

### CODE REVIEW

**Review by wassimj — APPROVED** [review]
Happy with this change. No issues.

**Comment by Krande** [comment]
@wassimj Just had a minor nitpick in my code that had forgotten to remove. Should be all done now! Sorry for the last minute commit

**Comment by Krande** [comment]
@wassimj Good news! Both topologicpy and topologic-core have been reviewed and approved for conda-forge distribution. Is there anyting else you wanted to do before merging this PR? Also, after merging, it would be great if you could make a tagged patch release. That'll automatically trigger a new release on conda-forge.

**Comment by wassimj** [comment]
> @wassimj Good news! Both topologicpy and topologic-core have been reviewed and approved for conda-forge distribution. Is there anyting else you wanted to do before merging this PR? Also, after merging, it would be great if you could make a tagged patch release. That'll automatically trigger a new release on conda-forge.

Great. I just pushed a tagged release. Can you please confirm if it has worked as expected? Unit tests take about 10-12 minutes to complete usually.

**Comment by Krande** [comment]
Will do! 

Btw. I noticed you tagged the topologicpy repo just now. Are you planning on tagging this repository also? :)

**Comment by wassimj** [comment]
Yes, will do next.

**Comment by Krande** [comment]
Looks like the unittests passed! 

FYI: I also looked at the latest tag you made on this repo; v8.0.1, but it seems to be from a separate branch `prerelease` which at the time was a few commits behind (so the tag did not include the patch in this PR).

**Comment by wassimj** [comment]
git confuses me to no end! Let me see where I went wrong

**Comment by Krande** [comment]
Topologic-core is now up on conda-forge: https://anaconda.org/conda-forge/topologic-core. Topologicpy is soon up.

**Comment by wassimj** [comment]
Glad it worked!!!

**Pull request merged**
